insomniacslk/dublin-traceroute

- .travis.yml
This fixed the build, https://travis-ci.org/insomniacslk/dublin-traceroute/builds/139060220
> New attempt to work around the travis/clang issue

- include/dublintraceroute/dublin_traceroute.h
- src/dublin_traceroute.cc
- src/main.cc
So that packets can be sent with a tunable interval
> Added --delay option

- go/dublintraceroute/net/icmp.go
- go/dublintraceroute/net/icmp_test.go
- go/dublintraceroute/net/ipv4.go
- go/dublintraceroute/net/ipv4_test.go
- go/dublintraceroute/net/layer.go
- go/dublintraceroute/net/protocols.go
- go/dublintraceroute/net/raw.go
- go/dublintraceroute/net/udp.go
- go/dublintraceroute/net/udp_test.go
- go/dublintraceroute/probes/probev4/udpv4.go
- go/dublintraceroute/probes/probev4/udpv4probe.go
Removed gopacket and used a custom, minimal implementation of ipv4, udp and icmpv4 protocols. More to come.
> Replaced gopacket with custom implementation

- go/dublintraceroute/probes/probev4/udpv4.go
- go/dublintraceroute/probes/probev4/udpv4probe.go
Probe matching is done in the response probe instead of the UDPv4 object
> Matching is in probe

- go/dublintraceroute/net/icmp.go
- go/dublintraceroute/net/icmpv6.go
- go/dublintraceroute/net/ipv4.go
- go/dublintraceroute/net/ipv4_test.go
- go/dublintraceroute/net/ipv6.go
- go/dublintraceroute/net/ipv6_test.go
- go/dublintraceroute/net/protocols.go
IPv6 and ICMP support in the net package
> go/net: added basic IPv6 and ICMP support

- go/dublintraceroute/probes/probev4/udpv4.go
- go/dublintraceroute/results/results.go
> [go] Fix compress function

- .gitignore
- go/dublintraceroute/probes/probev4/udpv4.go
- go/dublintraceroute/probes/probev4/udpv4probe.go
- go/dublintraceroute/probes/probev6/udpv6.go
- go/dublintraceroute/probes/probev6/udpv6probe.go
> fix V6 probe

- go/dublintraceroute/net/icmpv6.go
- go/dublintraceroute/probes/probev6/udpv6.go
This saves ~2.2MB from 7.6 to 5.4
> Replaced gopacket with custom library

- go/dublintraceroute/probes/probe.go
- go/dublintraceroute/probes/probev4/udpv4probe.go
- go/dublintraceroute/probes/probev6/udpv6.go
- go/dublintraceroute/probes/probev6/udpv6probe.go
> [go] added ProbeResponse.Matches

- go/dublintraceroute/cmd/dublin-traceroute/main.go
> Using unused variables

- .travis/docker/Dockerfile
- .travis/docker/build.sh
- .travis/docker/run.sh
> Added docker image

- .travis/docker/publish.sh
> Added docker/publish.sh

- documentation/readme/README.md
> Updated README to suggest using the Docker image

- .travis.yml
- .travis/install_dependencies_linux.sh
- include/dublintraceroute/dublin_traceroute.h
- include/dublintraceroute/hop.h
- src/dublin_traceroute.cc
- src/main.cc
- src/traceroute_results.cc
> Added --no-dns flag

- go/dublintraceroute/cmd/routest/config.json
- go/dublintraceroute/cmd/routest/main.go
- go/dublintraceroute/cmd/routest/reply.go
- go/dublintraceroute/cmd/routest/send.go
- go/dublintraceroute/cmd/routest/start.sh
- go/dublintraceroute/net/icmp.go
Added program to do integration testing of dublin-traceroute using
NFQUEUE
> Added RouTest

- .travis.yml
- .travis/install_dependencies_linux.sh
- go/dublintraceroute/cmd/dublin-traceroute/main.go
- go/dublintraceroute/probes/probev4/udpv4.go
- go/dublintraceroute/probes/probev6/udpv6.go
- go/dublintraceroute/results/results.go
- integ/integ_test.go
- integ/test_data/config_8.8.8.8_one_path.json
- integ/test_data/want_8.8.8.8_one_path.json
> Added integration tests using routest

- src/dublin_traceroute.cc
> Fix error when an exception is thrown in the listener thread

- go/dublintraceroute/cmd/routest/send.go
- go/dublintraceroute/net/icmp.go
- go/dublintraceroute/net/icmp_test.go
- go/dublintraceroute/net/icmpv6.go
- go/dublintraceroute/net/ipv4.go
- go/dublintraceroute/net/ipv4_test.go
- go/dublintraceroute/net/ipv6.go
- go/dublintraceroute/net/ipv6_test.go
- go/dublintraceroute/net/layer.go
- go/dublintraceroute/net/raw.go
- go/dublintraceroute/net/udp.go
- go/dublintraceroute/net/udp_test.go
- go/dublintraceroute/probes/probev4/udpv4.go
- go/dublintraceroute/probes/probev4/udpv4probe.go
- go/dublintraceroute/probes/probev6/udpv6.go
- go/dublintraceroute/probes/probev6/udpv6probe.go
- integ/integ_test.go
> Rename Marshal/Unmarshal to MarshalBinary/UnmarshalBinary

- documentation/readme/README.md
> Updated installation instructions for CentOS

- CMakeLists.txt
- documentation/readme/README.md
- homebrew/dublin-traceroute.rb
Added missing indirect dependencies, some cosmetic change, and updated README
> Fix build for macOS

- documentation/readme/README.md
> Fix README formatting

- .travis.yml
- .travis/docker/Dockerfile
- .travis/docker/publish.sh
- .travis/docker/run.sh
- documentation/readme/README.md
> [Docker] automatically push new image on docker hub

- go/dublintraceroute/cmd/dublin-traceroute/main.go
> [go/dublintraceroute] do not sort command line options

- README.md
> Update README to improve clarity

- docs/README.md
> Rephrased most of docs/README.md

- .github/workflows/tests.yml
- Dockerfile.integ
- go/dublintraceroute/probes/probev4/udpv4.go
- go/dublintraceroute/probes/probev6/udpv6.go
- go/dublintraceroute/results/results.go
- integ/integ_test.go
- integ/test_data/want_8.8.8.8_one_path.json
- src/hop.cc
This also helped fix several bugs:
* [go] results.UnixMsec.MarshalJSON did not compute values correctly
* [cpp] ICMP code and type were inverted in Hop::to_json
* [tests] wrong checks on received ICMP
> Run integration tests also for Go executable

- include/dublintraceroute/common.h
- include/dublintraceroute/dublin_traceroute.h
- include/dublintraceroute/hop.h
- include/dublintraceroute/hops.h
- include/dublintraceroute/traceroute_results.h
- include/dublintraceroute/udpv4probe.h
- src/dublin_traceroute.cc
- src/hop.cc
- src/main.cc
- src/traceroute_results.cc
- src/udpv4probe.cc
> Explicit use of Tins namespace

- .github/workflows/tests.yml
> [CI] Build Go version on macOS too

- docs/README.md
> Added feature matrix to README.md
